/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SlSidenav {
        "changeComponentCss": (incoming: any) => Promise<void>;
        "changeGlobalCss": (incoming: any) => Promise<void>;
        "theme": any;
        "width": any;
    }
    interface SlSidenavMaincontent {
    }
    interface SlSidenavPage {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSlSidenavElement extends Components.SlSidenav, HTMLStencilElement {
    }
    var HTMLSlSidenavElement: {
        prototype: HTMLSlSidenavElement;
        new (): HTMLSlSidenavElement;
    };
    interface HTMLSlSidenavMaincontentElement extends Components.SlSidenavMaincontent, HTMLStencilElement {
    }
    var HTMLSlSidenavMaincontentElement: {
        prototype: HTMLSlSidenavMaincontentElement;
        new (): HTMLSlSidenavMaincontentElement;
    };
    interface HTMLSlSidenavPageElement extends Components.SlSidenavPage, HTMLStencilElement {
    }
    var HTMLSlSidenavPageElement: {
        prototype: HTMLSlSidenavPageElement;
        new (): HTMLSlSidenavPageElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sl-sidenav": HTMLSlSidenavElement;
        "sl-sidenav-maincontent": HTMLSlSidenavMaincontentElement;
        "sl-sidenav-page": HTMLSlSidenavPageElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SlSidenav {
        "theme"?: any;
        "width"?: any;
    }
    interface SlSidenavMaincontent {
    }
    interface SlSidenavPage {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sl-sidenav": SlSidenav;
        "sl-sidenav-maincontent": SlSidenavMaincontent;
        "sl-sidenav-page": SlSidenavPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sl-sidenav": LocalJSX.SlSidenav & JSXBase.HTMLAttributes<HTMLSlSidenavElement>;
            "sl-sidenav-maincontent": LocalJSX.SlSidenavMaincontent & JSXBase.HTMLAttributes<HTMLSlSidenavMaincontentElement>;
            "sl-sidenav-page": LocalJSX.SlSidenavPage & JSXBase.HTMLAttributes<HTMLSlSidenavPageElement>;
        }
    }
}
